travis:
  secure:
    BINSTAR_TOKEN: i306zR+ZegTmGNU5QbY14GuNH3jUH0PUXVZlD3qxEJLIcemYmdHHxNbRxL77C9xZ0yxovr9DsO19buR83ShD03nLynieCmZxT0R1wVyErKaWtawFN/KKk7TQ1MXetJMBqdYlp4StO3VX2wzxtbdgcwY+J1J7zAVJ1EZxR3IAxD3EVOMJ+Gr7mtXV3ejNjoN0sZE2ljkJ/6dfj6PjHuZNV6DxCR/UYmrutzK8k+DmA4iUm5ea566PPsvBPPPc/aEHUkmAChrBMseLTFnf7sQfuN1D5p2lYlK/YRTylXq/mAE0PrgpeCvIhP9GgUtiIz1+ne897tPkyiz2beKMhyaPogTTDhl3kb9Vyf5jYIB4oD01GRsPmzb0q9m/TLkXgqElH6R2S1fW2PAtgSLqtM8KFXg1es+A3X6XaAbpHomYg0v5wcfVXYPTCZr1D7aMnLe+Z9rZUj3YnzQxO49H1oWWUNofeFxjaQHNHFHGJZA4kxZduvLfeUyWFC8n230MApI0KFu3PhnLPWx4pUEOLrVvNvZ4TJZ1zMIw7khIiUGLgxpxDjDqtQemeJRW9+sdfKpdQYK4PD4y9BTWl3tCEXFANlfXOXdY41hXfoaINNs2x4Qn0zN40Vgjq1UL5x61p55OXhCJO5CL0c+x4++6ROsOND7Pwi6mu3roOUl41EKdW8U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
